type Invoice @entity(immutable: false) {
  id: ID!
  invoiceId: String
  state: String
  createdAt: BigInt
  paidAt: BigInt
  seller: User
  buyer: User
  price: BigInt
  amountPaid: BigInt
  releasedAt: BigInt
  invalidateAt: BigInt
  expiresAt: BigInt
  releaseHash: Bytes
  paymentTxHash: Bytes
  fee: BigInt
  contract: Bytes
  creationTxHash: String
  commisionTxHash: Bytes
  refundTxHash: Bytes
  history: [String!]!
  historyTime: [String!]!
  lastActionTime: BigInt
}

type SmartInvoice @entity(immutable: false) {
  id: ID!
  buyer: User
  seller: User
  escrow: Bytes
  balance: BigInt
  paymentToken: PaymentToken
  paymentTxHash: Bytes
  releaseHash: Bytes
  state: String
  paidAt: BigInt
  releasedAt: BigInt
  createdAt: BigInt
  price: BigInt
  amountPaid: BigInt
  contract: Bytes!
  invoiceId: String
  creationTxHash: String
  refundTxHash: Bytes
  commisionTxHash: Bytes
  fee: BigInt
  lastActionTime: BigInt
}

type MetaInvoice @entity(immutable: false) {
  id: ID!
  invoiceId: String
  buyer: User
  price: BigInt
  contract: Bytes!
}

type User @entity(immutable: false) {
  id: ID!
  ownedInvoices: [Invoice!]! @derivedFrom(field: "seller")
  paidInvoices: [Invoice!]! @derivedFrom(field: "buyer")
  issuedInvoices: [SmartInvoice!]! @derivedFrom(field: "seller")
  receivedInvoices: [SmartInvoice!]! @derivedFrom(field: "buyer")
  metaInvoices: [MetaInvoice!]! @derivedFrom(field: "buyer")
}

type AdminAction @entity(immutable: false) {
  id: ID!
  invoiceId: String
  action: String
  time: BigInt
  type: String
  txHash: String
  balance: BigInt
  currency: PaymentToken
}

type PaymentToken @entity(immutable: false) {
  id: ID!
  name: String
  decimal: String
}

type Type @entity(immutable: false) {
  id: ID!
  type: String!
}
