type SimplePaymentProcessor @entity(immutable: false) {
  id: ID!
  invoiceNonce: String
  state: String
  createdAt: BigInt
  paidAt: BigInt
  seller: User
  buyer: User
  price: BigInt
  amountPaid: BigInt
  releasedAt: BigInt
  invalidateAt: BigInt
  expiresAt: BigInt
  releaseHash: Bytes
  paymentTxHash: Bytes
  fee: BigInt
  contract: Bytes
  creationTxHash: String
  commissionTxHash: Bytes
  refundTxHash: Bytes
  history: [String!]!
  historyTime: [String!]!
  lastActionTime: BigInt
  buyerNote: String
  sellerNote: String
}

type AdvancedPaymentProcessor @entity(immutable: false) {
  id: ID!
  invoiceNonce: String
  buyer: User
  seller: User
  escrow: Bytes
  balance: BigInt
  paymentToken: PaymentToken
  paymentTxHash: Bytes
  releaseHash: Bytes
  state: String
  paidAt: BigInt
  releasedAt: BigInt
  createdAt: BigInt
  price: BigInt
  amountPaid: BigInt
  contract: Bytes!
  creationTxHash: String
  refundTxHash: Bytes
  commissionTxHash: Bytes
  fee: BigInt
  history: [String!]!
  historyTime: [String!]!
  lastActionTime: BigInt
  buyerNote: String
  sellerNote: String
}

type MetaInvoice @entity(immutable: false) {
  id: ID!
  invoiceId: String
  buyer: User
  price: BigInt
  contract: Bytes!
}

type User @entity(immutable: false) {
  id: ID!
  ownedInvoices: [SimplePaymentProcessor!]! @derivedFrom(field: "seller")
  paidInvoices: [SimplePaymentProcessor!]! @derivedFrom(field: "buyer")
  issuedInvoices: [AdvancedPaymentProcessor!]! @derivedFrom(field: "seller")
  receivedInvoices: [AdvancedPaymentProcessor!]! @derivedFrom(field: "buyer")
  metaInvoices: [MetaInvoice!]! @derivedFrom(field: "buyer")
}

type AdminAction @entity(immutable: false) {
  id: ID!
  invoiceNonce: String
  action: String
  time: BigInt
  category: String
  txHash: String
  balance: BigInt
  currency: PaymentToken
}

type PaymentToken @entity(immutable: false) {
  id: ID!
  name: String
  decimal: String
}

type InvoiceType @entity(immutable: false) {
  id: ID!
  type: String!
}

type Note @entity(immutable: false) {
  id: ID!
  invoiceId: BigInt!
  noteId: BigInt!
  author: Bytes!
  share: Boolean!
  encryptedContent: Bytes!
  createdAtBlock: BigInt!
  createdAtTx: Bytes!
}

type NoteOpenState @entity(immutable: false) {
  id: ID!
  invoiceId: BigInt!
  noteId: BigInt!
  user: Bytes!
  opened: Boolean!
  updatedAtBlock: BigInt!
  updatedAtTx: Bytes!
}
